apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: workload-suite
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-ui-pdb
  namespace: workload-suite
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend-ui
