apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-logger
  namespace: workload-suite
  labels:
    app: node-logger
spec:
  selector:
    matchLabels:
      app: node-logger
  template:
    metadata:
      labels:
        app: node-logger
    spec:
      serviceAccountName: node-logger-sa
      priorityClassName: low-priority
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
            type: DirectoryOrCreate
        - name: temp-buffer
          emptyDir: {}
      containers:
        - name: fluentbit
          image: fluent/fluent-bit:2.2
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: temp-buffer
              mountPath: /fluent-bit/buffer
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: logger-config
                  key: es-host
            - name: FLUENT_ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: logger-config
                  key: es-port
