apiVersion: v1
kind: Service
metadata:
  name: stateful-db-headless
  namespace: workload-suite
  labels:
    app: stateful-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None                          
  selector:
    app: stateful-db
