apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: workload-suite
  labels:
    app: frontend-ui
spec:
  selector:
    app: frontend-ui
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
