apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-db
  namespace: workload-suite
  labels:
    app: stateful-db
spec:
  serviceName: stateful-db-headless        
  replicas: 2
  selector:
    matchLabels:
      app: stateful-db
  template:
    metadata:
      labels:
        app: stateful-db
    spec:
      serviceAccountName: db-access-sa
      terminationGracePeriodSeconds: 30
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: gp2
